export default [
  {
    content: [
      "Introduction: While some argue that technology has led to greater isolation, others believe it fosters stronger connections. This essay will examine both perspectives before concluding with my opinion.",
      "Body 1: To begin with, technology can contribute to social isolation. Excessive screen time reduces face-to-face interaction. For example, studies reveal that many teenagers spend more time online than engaging with peers in person. Consequently, social media overuse may lead to loneliness, mental health problems, and weakened real-life relationships.",
      "Body 2: Nevertheless, technology can also strengthen relationships. Instant communication across distances allows families and friends to remain close through video calls and messaging apps. For instance, immigrants often rely on WhatsApp or Zoom to stay connected with loved ones, while international companies benefit from tools like Slack and Teams to support collaboration across borders.",
      "Conclusion: In conclusion, although technology can sometimes cause isolation, I believe its potential to connect people worldwide outweighs its disadvantages."
    ],
    fullExample: `Some people think technology isolates people, while others believe it brings people closer together. Discuss both views and give your opinion.\n\nWhile some argue that technology has led to greater isolation, others believe it fosters stronger connections. This essay will examine both perspectives before concluding with my opinion.\n\nTo begin with, technology can contribute to social isolation. Excessive screen time reduces face-to-face interaction. For example, studies reveal that many teenagers spend more time online than engaging with peers in person. Consequently, social media overuse may lead to loneliness, mental health problems, and weakened real-life relationships.\n\nNevertheless, technology can also strengthen relationships. Instant communication across distances allows families and friends to remain close through video calls and messaging apps. For instance, immigrants often rely on WhatsApp or Zoom to stay connected with loved ones, while international companies benefit from tools like Slack and Teams to support collaboration across borders.\n\nIn conclusion, although technology can sometimes cause isolation, I believe its potential to connect people worldwide outweighs its disadvantages.`
  },
  {
    content: [
      "Introduction: The question of whether technology divides or unites people remains a subject of debate. This essay will discuss both viewpoints before presenting my perspective.",
      "Body 1: On one hand, technology can isolate individuals. People may spend countless hours on their phones or computers rather than interacting with those around them. This overreliance on devices can weaken face-to-face relationships and increase feelings of loneliness.",
      "Body 2: On the other hand, technology enables people to maintain meaningful connections over long distances. Social media platforms and messaging applications allow friends and families to stay in contact regardless of geography. Moreover, such tools promote cultural exchange and understanding between diverse communities.",
      "Conclusion: In my view, while technology may occasionally contribute to isolation, its capacity to build and sustain relationships across borders is more significant, particularly when used responsibly."
    ],
    fullExample: `Some people think technology isolates people, while others believe it brings people closer together. Discuss both views and give your opinion.\n\nThe question of whether technology divides or unites people remains a subject of debate. This essay will discuss both viewpoints before presenting my perspective.\n\nOn one hand, technology can isolate individuals. People may spend countless hours on their phones or computers rather than interacting with those around them. This overreliance on devices can weaken face-to-face relationships and increase feelings of loneliness.\n\nOn the other hand, technology enables people to maintain meaningful connections over long distances. Social media platforms and messaging applications allow friends and families to stay in contact regardless of geography. Moreover, such tools promote cultural exchange and understanding between diverse communities.\n\nIn my view, while technology may occasionally contribute to isolation, its capacity to build and sustain relationships across borders is more significant, particularly when used responsibly.`
  },
  {
    content: [
      "Introduction: Technology's influence on human connection is controversial. This essay will examine arguments from both sides before giving my own opinion.",
      "Body 1: Critics argue that technology reduces the quality of interaction. Online conversations often lack the depth and emotional nuance of face-to-face communication. Furthermore, constant device use may erode social skills and diminish people’s ability to form strong relationships in real life.",
      "Body 2: Supporters, however, contend that technology connects people in powerful ways. Platforms such as video conferencing, online communities, and collaborative tools enable individuals to share experiences and work together across the globe. These opportunities would be impossible without modern technology.",
      "Conclusion: Overall, although technology has some drawbacks, I am convinced that it enhances social connection and provides valuable opportunities for global interaction."
    ],
    fullExample: `Some people think technology isolates people, while others believe it brings people closer together. Discuss both views and give your opinion.\n\nTechnology's influence on human connection is controversial. This essay will examine arguments from both sides before giving my own opinion.\n\nCritics argue that technology reduces the quality of interaction. Online conversations often lack the depth and emotional nuance of face-to-face communication. Furthermore, constant device use may erode social skills and diminish people’s ability to form strong relationships in real life.\n\nSupporters, however, contend that technology connects people in powerful ways. Platforms such as video conferencing, online communities, and collaborative tools enable individuals to share experiences and work together across the globe. These opportunities would be impossible without modern technology.\n\nOverall, although technology has some drawbacks, I am convinced that it enhances social connection and provides valuable opportunities for global interaction.`
  }
];
